server:
    port: 17003
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: ''
        url: jdbc:mysql://127.0.0.1:3306/parts_rm?characterEncoding=UTF-8
        username: root
    profiles:
        active: mysql
    redis:
        host: 10.100.2.106
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
        port: 6379
test-env: true
version: 1.0.1-SNAPSHOT